version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
  pre_build:
    commands:
      - yarn install
  build:
    commands:
      - yarn build
artifacts:
  files:
    - build/**/*
    - package.json
    - .platform/**/*
